# Generated by Django 5.2.6 on 2025-10-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_wage', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('overtime_wage', models.DecimalField(decimal_places=2, default=60, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(choices=[('shift1', 'Shift1'), ('shift2', 'Shift2')], default='shift1', max_length=10)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('leaving_time', models.TimeField(blank=True, null=True)),
                ('overtime', models.BooleanField(default=False)),
                ('overtime_entry_time', models.TimeField(blank=True, null=True)),
                ('overtime_leaving_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='No work description.', null=True)),
                ('worker_response', models.CharField(choices=[('satisfied', 'Safisfied'), ('report', 'Report'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Users.employermodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Users.workermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReportWorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='No message regarding report by worker.', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('salary', 'Salary'), ('attendance', 'Attendance'), ('behaviour', 'Behaviour'), ('other', 'Other')], default='other', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Worker.attendences')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Users.employermodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Users.workermodel')),
            ],
        ),
    ]
