# Generated by Django 5.2.6 on 2025-10-08 00:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendences',
            name='work_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
