# Generated by Django 5.2.6 on 2025-09-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_workermodel_employer'),
        ('Worker', '0002_attendences_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendences',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Users.employermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendences',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendences',
            name='overtime_entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendences',
            name='overtime_leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendences',
            name='shift',
            field=models.CharField(choices=[('shift1', 'Shift1'), ('shift2', 'Shift2')], default='shift1', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendences',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendences',
            name='leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendences',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Users.workermodel'),
        ),
    ]
