# Generated by Django 5.2.6 on 2025-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_attendences_employer_attendences_overtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_wage', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('overtime_wage', models.DecimalField(decimal_places=2, default=60, max_digits=10)),
            ],
        ),
    ]
