# Generated by Django 5.2.6 on 2025-09-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0004_hourrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HourRate',
            new_name='HourWage',
        ),
    ]
