# Generated by Django 5.2.6 on 2025-09-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_workermodel_employer'),
        ('Worker', '0005_rename_hourrate_hourwage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='No message regarding report.', null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Users.employermodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Users.workermodel')),
            ],
        ),
    ]
