# Generated by Django 5.2.6 on 2025-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0006_reportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='reason',
            field=models.CharField(choices=[('salary', 'Salary'), ('attendance', 'Attendance'), ('behaviour', 'Behaviour'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
