# Generated by Django 5.2.6 on 2025-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0007_reportmodel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
