# Generated by Django 5.2.6 on 2025-09-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_workermodel_employer'),
        ('Worker', '0008_reportmodel_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportModel',
            new_name='ReportWorkerModel',
        ),
    ]
