# Generated by Django 5.2.6 on 2025-09-30 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0009_rename_reportmodel_reportworkermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportworkermodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 30, 18, 24, 1, 946769)),
            preserve_default=False,
        ),
    ]
