# Generated by Django 5.2.6 on 2025-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0010_reportworkermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportworkermodel',
            name='message',
            field=models.TextField(blank=True, default='No message regarding report by worker.', null=True),
        ),
    ]
