# Generated by Django 5.2.6 on 2025-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0011_alter_reportworkermodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendences',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
