# Generated by Django 5.2.6 on 2025-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0012_attendences_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendences',
            name='description',
            field=models.TextField(blank=True, default='No work description.', null=True),
        ),
    ]
