# Generated by Django 5.2.6 on 2025-10-13 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Username must be at least 5 characters long.'), django.core.validators.RegexValidator(message='Username may contain only letters, numbers, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
        ),
    ]
