# Generated by Django 5.2.6 on 2025-09-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_workermodel_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermodel',
            name='employer',
        ),
    ]
