# Generated by Django 5.2.6 on 2025-10-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EChowk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chowkId', models.CharField(max_length=10)),
                ('chowk_name', models.CharField(max_length=20)),
                ('chowk_code', models.CharField(max_length=20)),
                ('chowk_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('chowk_type', models.CharField(choices=[('construction', 'Construction'), ('market', 'Market'), ('industrial', 'Industrial'), ('rural', 'Rural'), ('other', 'Other')], max_length=20)),
                ('chowk_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workermodel',
            name='chowk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chowk', to='Users.echowk'),
        ),
    ]
