# Generated by Django 5.2.6 on 2025-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_workermodel_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
