# Generated by Django 5.2.6 on 2025-10-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_workermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
