# Generated by Django 5.2.6 on 2025-10-29 11:59

import Users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_echowk_workermodel_chowk'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerExtendedRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('registration_type', models.CharField(choices=[('e_chowk', 'e-CHOWK'), ('samagra', 'Samagra'), ('esic', 'ESIS/ESIC'), ('health_card', 'Health Card')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='echowk',
            name='chowkId',
            field=models.CharField(default=Users.models.generate_chowk_id, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='echowk',
            name='chowk_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='echowk',
            name='chowk_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='echowk',
            name='chowk_type',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('market', 'Market'), ('industrial', 'Industrial'), ('rural', 'Rural'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='echowk',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='chowk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='Users.echowk'),
        ),
    ]
