# Generated by Django 5.2.6 on 2025-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_workermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermodel',
            name='contact_number',
            field=models.CharField(default=9876543210, max_length=10),
            preserve_default=False,
        ),
    ]
