# Generated by Django 5.2.6 on 2025-10-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employer', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemployermodel',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reports', to='Users.employermodel'),
        ),
        migrations.AddField(
            model_name='reportemployermodel',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_reports', to='Users.workermodel'),
        ),
        migrations.AddField(
            model_name='workersworkmodel',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Users.employermodel'),
        ),
        migrations.AddField(
            model_name='workersworkmodel',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Users.workermodel'),
        ),
    ]
