# Generated by Django 5.2.6 on 2025-09-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_alter_connections_unique_together_and_more'),
        ('Users', '0003_remove_workermodel_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersworkmodel',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Users.employermodel'),
        ),
        migrations.AlterField(
            model_name='workersworkmodel',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Users.workermodel'),
        ),
        migrations.CreateModel(
            name='ReportEmployerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('salary', 'Salary'), ('behaviour', 'Behaviour'), ('other', 'Other')], default='other', max_length=10)),
                ('message', models.TextField(blank=True, default='No message regarding report by Employer.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reports', to='Users.employermodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reports', to='Users.workermodel')),
            ],
        ),
    ]
