# Generated by Django 5.2.6 on 2025-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersworkmodel',
            name='overtime_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workersworkmodel',
            name='working_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
