# Generated by Django 5.2.6 on 2025-10-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_workersworkmodel_overtime_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workersworkmodel',
            old_name='overtime_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='workersworkmodel',
            name='working_amount',
        ),
    ]
