# Generated by Django 5.2.6 on 2025-09-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_alter_workersworkmodel_employer_and_more'),
        ('Users', '0003_remove_workermodel_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemployermodel',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_reports', to='Users.workermodel'),
        ),
    ]
