# Generated by Django 5.2.6 on 2025-10-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_rename_overtime_amount_workersworkmodel_amount_and_more'),
        ('Worker', '0002_attendences_work_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersworkmodel',
            name='attendance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='Worker.attendences'),
            preserve_default=False,
        ),
    ]
