# Generated by Django 5.2.6 on 2025-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_workersworkmodel_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersworkmodel',
            name='amount_given',
            field=models.BooleanField(default=False),
        ),
    ]
