# Generated by Django 5.2.6 on 2025-09-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
        ('Users', '0002_alter_workermodel_employer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connections',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='connections',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='connections',
            name='worker',
        ),
        migrations.CreateModel(
            name='WorkersWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_name', to='Users.employermodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_name', to='Users.workermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ConnectionRequest',
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
    ]
