# Generated by Django 5.2.6 on 2025-09-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_alter_workermodel_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('leaving_time', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='Users.workermodel')),
            ],
        ),
    ]
