# Generated by Django 5.2.6 on 2025-10-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Worker', '0002_attendences_work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedReportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_message', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Worker.reportworkermodel')),
            ],
        ),
    ]
